Interrupt publishing to deprecated streams
postmates/triton-python pull request #39
Opened 2020-12-08 00:44 UTC by alecraso

There are only two remaining streams that are still being read from in
production (courier_event and delivery_event). We don't need to publish
any event to any other stream, so we can just throw those events away
as they are sent to tritond.

This can be done as a lightweight way to allow for the shutdown of
the kinesis streams ($$) without having to comb through thousands of
lines of code across dozens of repositories to remove all publishes to
triton. That can be done safely at a later time.

2020-12-08 01:02 UTC, dharamsk requested changes
there are lots of other streams that publish to triton that fleet uses. We either need to add them to the white list or make a blacklist.

2020-12-08 03:00 UTC, aabhassharma approved these changes

2020-12-09 18:47 UTC, dharamsk approved these changes

2020-12-09 18:47 UTC, dharamsk commented on bin/tritond
> +STATSD_SKIPCOUNT = STATSD_PREFIX + "skipcount."
this won't do anything in gke

2020-12-09 22:26 UTC, merged

2020-12-11 18:47 UTC, dharamsk commented on bin/tritond
> +    'courier_event ',
LOL 🤦